server:
  port: 7001
spring:
  application:
    name: spring-cloud-consumer
  main:
    allow-bean-definition-overriding: true
  # 防止依赖冲突
#  autoconfigure:
#    exclude: org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration
## nacos 配置
#  cloud:
#    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yml
#      discovery:
#        server-addr: 127.0.0.1:8848

# eureka 配置
eureka:
  instance:
    appname: spring-cloud-consumer
    prefer-ip-address: false
    instance-id: ${eureka.instance.appname}-${server.port}
    hostname: ${eureka.instance.appname}-${server.port}
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://spring-cloud-eureka-8761:8761/eureka/,http://spring-cloud-eureka-8762:8762/eureka/,http://spring-cloud-eureka-8763:8763/eureka/
# actuator info 配置
info:
  app.name: springcloud
  company.name: weisenzcharles