server:
  port: 8585
# mybatis 配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.charles.springcloud.api.entity
# spring 配置
spring:
  application:
    name: spring-cloud-provider-consul
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.123:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: spring-cloud-provider-consul
        service-name: spring-cloud-provider # 当前应用注册到 consul 的名称
        prefer-ip-address: true # 注册 IP

#        healthCheckPath: ${management.server.servlet.context-path}/actuator/health
#        healthCheckInterval: 15s
#        health-check-headers:
#          X-Config-Token: 6442e58b-d1ea-182e-cfa5-cf9cddef0722
#        prefer-ip-address: true
