server:
  port: 8001
# mybatis 配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.charles.springcloud.api.entity

# spring 配置
spring:
  application:
    name: spring-cloud-provider
  # 防止依赖冲突
  autoconfigure:
    exclude: org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.123:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
# nacos 配置
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
# eureka 配置
eureka:
  instance:
    hostname: ${eureka.instance.appname}-${server.port}
    instance-id: ${eureka.instance.appname}-${server.port}
    prefer-ip-address: false
  client:
    service-url:
      #      defaultZone: http://localhost:9001/eureka/
      # 集群
      defaultZone: http://spring-cloud-eureka-8761:8761/eureka/,http://spring-cloud-eureka-8762:8762/eureka/,http://spring-cloud-eureka-8763:8763/eureka/