server:
  port: 7071
spring:
  application:
    name: spring-cloud-consumer
# nacos 配置
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
      discovery:
        server-addr: 127.0.0.1:8848
