spring:
  datasource:
    customer:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.86:3306/customer?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        connection-test-query: SELECT 1 FROM DUAL
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 60000
        connection-timeout: 30000
    product:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.86:3306/product?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        connection-test-query: SELECT 1 FROM DUAL
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 60000
        connection-timeout: 30000
  jpa:
    customer:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      open-in-view: true
    product:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      open-in-view: true

#    hibernate:
#      dialect:
#        storage_engine: InnoDB  # 配置开启 InnoDB 引擎
#      ddl-auto: update  # 配置自动更新表结构
#    generate-ddl: true  # 配置生成数据库表结构
#    show-sql: true  # 配置显示 SQL 语句
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect # 配置使用 MySQL 5.7 版本
#    open-in-view: true