server:
  port: 8762
# eureka 配置
eureka:
  instance:
    appname: spring-cloud-eureka
    hostname: ${eureka.instance.appname}-${server.port}
    instance-id: ${eureka.instance.appname}-${server.port}
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      # 单机
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群
      defaultZone: http://spring-cloud-eureka-8761:8761/eureka/,http://spring-cloud-eureka-8763:8763/eureka/