
spring:
  redis:
    database: 0
    host: 192.168.0.123
    port: 6379
    #    password: 123456
    timeout: 5000
    lettuce:
      shutdown-timeout: 200
      pool:
        max-active: 500
        max-idle: 100
        min-idle: 50
        max-wait: 2000
server:
  port: 9989