server:
  port: 8888
spring:
  application:
    name: spring-boot-jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.86:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
  jpa:
    hibernate:
      dialect:
        storage_engine: InnoDB  # 配置开启 InnoDB 引擎
      ddl-auto: update  # 配置自动更新表结构
    generate-ddl: true  # 配置生成数据库表结构
    show-sql: true  # 配置显示 SQL 语句
    database-platform: org.hibernate.dialect.MySQL57Dialect # 配置使用 MySQL 5.7 版本
    open-in-view: true
logging:
  level:
    org.charles.springboot.jpa: debug # 配置项目日志级别
    org.hibernate.SQL: debug
    org.hibernate.type: trace